### ISSUE TITLE
Could not find module 'WebimMobileWidget' for target 'x86_64-apple-ios-simulator'; 

### ISSUE THREAD

**Issue by BekNaji** [webim/webim-mobile-ui-ios#4]
Здравствуйте,
Я пытаюсь подключить WebimMobileWidget к своему проекту, но появилась эта ошибка. Как решить эту проблему ?

Я сделал так, как написано в документации
https://webim.ru/kb/mobile/webim-widget/ios-widget-install.html

Could not find module 'WebimMobileWidget' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: ...Library/Developer/Xcode/DerivedData/Runner-ahijaoqbhfmonadibapibsqwalhw/Index.noindex/Build/Products/Debug-iphonesimulator/WebimMobileWidget.swiftmodule](..Library/Developer/Xcode/DerivedData/Runner-ahijaoqbhfmonadibapibsqwalhw/Index.noindex/Build/Products/Debug-iphonesimulator/WebimMobileWidget.swiftmodule)

**Comment by webim** [comment]
Здравствуйте. Попробуйте поменять значение Build Active Architecture Only в Build Settings проекта на противоположное значение. Ещё можно попробовать удалить кэш и derived data.
Если ошибка останется, то сообщите версию Xcode и какой процессор компьютера: Intel или Apple Silicon.

**Comment by BekNaji** [comment]
Я решил эту проблему. Спасибо, я указал IPHONEOS_DEPLOYMENT_TARGET = 12 и запустил с Rosetta, тогда все заработало.
